data:
  features: ./datasets/cl-8h/features.txt
  path: ./datasets/cl-8h/4i-melanoma_cell_lines-8h.h5ad
  condition: drug
  source: control
  type: cell

dataloader:
  batch_size: 256
  shuffle: true

datasplit:
  groupby: drug
  name: train_test
  test_size: 0.2
