defaults:
  - pred_x_0

LATENT_DIM: null #deprecated.
COND_CLASSES: 115 #114 in adata.obs.perturbation, add one for NaNs.

score_network:
  cond_classes: ${COND_CLASSES}
  input_dim: 50
  embed_data_dim: 256
  model_dim: 512
  n_layers: 2
  final_layers: 256

dataloader:
  batch_size: 8192
  num_workers: 64

data:
  type: scPerturb
  path: /Mounts/rbg-storage1/users/johnyang/cellot/datasets/AdamsonWeissman2016_GSM2406681_10X010.h5ad
  pca: True